
name: Build & Release (Windows MSI)

on:
  push:
    branches: [main]   # build every commit to main
    tags:    ['*']     # and any tag
  workflow_dispatch:
    inputs:
      version:
        description: "Release version when run manually"
        required: true
        default: "dev"

permissions:
  contents: write

jobs:
  msi:
    runs-on: windows-latest

    # One variable that covers all situations:
    # • tag build         -> tag name   (e.g. v1.2.0)
    # • manual dispatch   -> input      (e.g. 1.2.0-rc1)
    # • main commit build -> commit sha (short) or 'dev'
    env:
      RELEASE_VERSION: >-
        ${{ github.event_name == 'workflow_dispatch'
            && inputs.version
            || startsWith(github.ref, 'refs/tags/')
            && github.ref_name
            || github.sha }}

    steps:
    - uses: actions/checkout@v4

    # Toolchain
    - uses: microsoft/setup-msbuild@v1.1

    # Build exe
    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build gcode_gen.exe
      shell: pwsh
      run: cmake --build build --config Release

    # Prepare dist
    - name: Prepare dist folder
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force dist 2>$null
        New-Item -ItemType Directory -Path dist | Out-Null

    # WiX v4 CLI
    - name: Install WiX Toolset
      shell: pwsh
      run: dotnet tool install --global wix --version 4.*

    # Pack MSI
    - name: Pack MSI
      shell: pwsh
      run: |
        wix build wix/installer.wxs `
                 -arch x64 `
                 -out dist/gcode_gen-${{ env.RELEASE_VERSION }}-x64.msi

    # Upload MSI as build artifact so you can grab it from
    # non-release runs (e.g. every commit to main).
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gcode_gen-msi
        path: dist/*.msi

    # Create / update GitHub Release **only** on tag or manual dispatch
    - name: Publish GitHub release
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: gcode_gen ${{ env.RELEASE_VERSION }}
        generate_release_notes: true
        files: |
          dist/gcode_gen-${{ env.RELEASE_VERSION }}-x64.msi
