name: Build & Release (Windows MSI)

on:
  push:
    branches: [main]     # build every commit on main
    tags:     ['*']      # build every tag (e.g. v1.2.0)
  workflow_dispatch:
    inputs:
      version:
        description: "Release version when run manually"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: read         # needed if you pull/push GHCR images elsewhere
  # ↑ keeping packages:read is handy if you ever add docker steps

jobs:
  msi:
    runs-on: windows-latest

    # Resolve RELEASE_VERSION once, usable in every step
    env:
      RELEASE_VERSION: >-
        ${{ github.event_name == 'workflow_dispatch'
            && inputs.version
            || startsWith(github.ref, 'refs/tags/')
            && github.ref_name
            || github.sha }}

    steps:
    # ------------------------------
    # 1. Fetch source
    # ------------------------------
    - uses: actions/checkout@v4

    # ------------------------------
    # 2. MSBuild / toolchain for CMake
    # ------------------------------
    - uses: microsoft/setup-msbuild@v1.1

    # ------------------------------
    # 3. Configure + build
    # ------------------------------
    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build gcode_gen.exe
      shell: pwsh
      run: cmake --build build --config Release

    # ------------------------------
    # 4. Prepare dist folder (robust)
    # ------------------------------
    - name: Prepare dist folder
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Path dist | Out-Null

    # ------------------------------
    # 5. Install WiX v4 CLI
    # ------------------------------
    - name: Install WiX Toolset
      shell: pwsh
      run: dotnet tool install --global wix --version 4.*

    # ------------------------------
    # 6. Build the MSI
    # ------------------------------
    - name: Pack MSI
      shell: pwsh
      run: |
        wix build wix/installer.wxs `
                 -arch x64 `
                 -out dist/gcode_gen-${{ env.RELEASE_VERSION }}-x64.msi

    # ------------------------------
    # 7. Save MSI as workflow artifact
    # ------------------------------
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gcode_gen-msi
        path: dist/*.msi

    # ------------------------------
    # 8. Create / update GitHub Release (only for tag or manual)
    # ------------------------------
    - name: Publish GitHub release
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: gcode_gen ${{ env.RELEASE_VERSION }}
        generate_release_notes: true
        files: |
          dist/gcode_gen-${{ env.RELEASE_VERSION }}-x64.msi
