name: Build & Release (Windows MSI)

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch:
    inputs:
      version:
        description: "Release version when run manually"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: read

jobs:
  msi:
    runs-on: windows-latest
    env:
      RAW_VERSION: >-
        ${{ github.event_name == 'workflow_dispatch'
            && inputs.version
            || startsWith(github.ref, 'refs/tags/')
            && github.ref_name
            || github.sha }}

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v1.1

    - name: Configure CMake
      shell: pwsh
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build gcode_gen.exe
      shell: pwsh
      run: cmake --build build --config Release

    # ----------------------------------------------------------------
    # Compute a WiX-legal version string
    # ----------------------------------------------------------------
    - name: Compute version
      id: ver
      shell: pwsh
      run: |
        $raw = "${{ env.RAW_VERSION }}"
        if ($raw -match '^refs/tags/(.+)') { $raw = $Matches[1] }
        if ($raw.StartsWith('v')) { $raw = $raw.Substring(1) }
        $isSemVer = $raw -match '^\d+\.\d+\.\d+(\.\d+)?(-[0-9A-Za-z\-.]+(\.\d+)?)?$'
        if (-not $isSemVer) { $raw = "0.0.${{ github.run_number }}.0" }
        echo "safe=$raw" >> $env:GITHUB_OUTPUT

    - name: Prepare dist folder
      shell: pwsh
      run: |
        Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Path dist | Out-Null

    - name: Install WiX Toolset
      shell: pwsh
      run: dotnet tool install --global wix --version 4.*

    # ----------------------------------------------------------------
    # Harvest every file in the Release directory -> build_files.wxs
    # ----------------------------------------------------------------
    - name: Harvest build output
      shell: pwsh
      run: |
        $buildDir = "${{ github.workspace }}\build\src\gcode_gen\Release"
        wix harvest directory `
          -var BuildDir `
          -id BuildOutput `
          -cg BuildComponents `
          -dr PRODUCTDIR `
          -o build_files.wxs `
          $buildDir

    # ----------------------------------------------------------------
    # Build the MSI using installer.wxs + harvested build_files.wxs
    # ----------------------------------------------------------------
    - name: Pack MSI
      shell: pwsh
      run: |
        $buildDir = "${{ github.workspace }}\build\src\gcode_gen\Release"
        $version  = "${{ steps.ver.outputs.safe }}"
        wix build wix\installer.wxs build_files.wxs `
            -arch x64 `
            -d "Version=$version" `
            -d "BuildDir=$buildDir" `
            -out "dist\gcode_gen-$version-x64.msi"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gcode_gen-msi
        path: dist\*.msi

    - name: Publish GitHub release
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.ver.outputs.safe }}
        name: gcode_gen ${{ steps.ver.outputs.safe }}
        generate_release_notes: true
        files: |
          dist\gcode_gen-${{ steps.ver.outputs.safe }}-x64.msi
